# Generated by Django 6.0.3 on 2026-04-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
