# Generated by Django 6.0.3 on 2026-05-07 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_restaurant_created_at_restaurant_is_featured_and_more"),
        ("main", "0007_restaurant_owner"),
    ]

    operations = []
